---
all:
  vars:
    # Network config variables
    homelab_netmask: "255.255.255.0"
    homelab_gateway: "192.168.10.1"
    homelab_dns_servers: [
      "192.168.10.10",
      "192.168.10.11",
      "192.168.10.12",
      "192.168.10.13",
    ]
    homelab_domain: "starnes.cloud"

    # Nomad variables
    nomad_dc: "homelab"

    # Temporary vars while working
    admin_password: asdfb
    temp_dns_servers: ["8.8.8.8", "8.8.4.4"]

  hosts:
    nephilim:
      ansible_host: 192.168.10.1
      ansible_python_interpreter: /usr/bin/python3
      nfs: 'server'
    PL-NOMAD-00:
      # DC:A6:32:C4:F5:38
      ansible_host: 192.168.10.10
      ansible_python_interpreter: /usr/bin/python3
      nfs: 'client'
      consul_leader: true
      nomad_leader: true
      consul_node_number: '0'
    #PL-NOMAD-01:
    #  # DC:A6:32:19:48:C1
    #  ansible_host: 192.168.10.11
    #  ansible_python_interpreter: /usr/bin/python3
    #  nfs: 'client'
    #  consul_leader: false
    #  nomad_leader: false
    #  consul_node_number: '1'
    PL-NOMAD-02:
      # DC:A6:32:DC:98:95
      ansible_host: 192.168.10.12
      ansible_python_interpreter: /usr/bin/python3
      nfs: 'client'
      consul_leader: false
      nomad_leader: false
      consul_node_number: '2'
    # Printer
    #    # 38:22:E2:D6:4F:AC
    #    host: 192.168.10.200
    PL-NOMAD-03:
      # B8:27:EB:98:83:C2
      ansible_host: 192.168.10.13
      ansible_python_interpreter: /usr/bin/python3
      nfs: 'client'
      consul_leader: false
      nomad_leader: false
      consul_node_number: '3'
  children:
    workstations:
      hosts:
        nephilim:
    servers:
      hosts:
        #PL-NOMAD-[00:03]:
        PL-NOMAD-00:
        PL-NOMAD-02:
        PL-NOMAD-03:
    consul:
      hosts:
        #PL-NOMAD-[00:03]:
        PL-NOMAD-00:
          consul_dc: "homelab"
          consul_domain: "consul"
        PL-NOMAD-02:
          consul_dc: "homelab"
          consul_domain: "consul"
        PL-NOMAD-03:
          consul_dc: "homelab"
          consul_domain: "consul"
    nomad:
      hosts:
        #PL-NOMAD-[00:03]:
        PL-NOMAD-00:
        PL-NOMAD-02:
        PL-NOMAD-03:
    vault:
      hosts:
        #PL-NOMAD-[00:02]:
        PL-NOMAD-00:
        PL-NOMAD-02:
