---
# tasks file for sft.vault
- name: Install Vault dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - curl
      - gnupg
    state: latest

- name: Add Hashicorp GPG key
  become: true
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp.asc
    mode: '0644'
    force: true

- name: Add Hashicorp repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64 signed-by=/usr/share/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com bookworm main
    filename: hashicorp
    state: present
    update_cache: true

- name: Install Vault
  become: true
  ansible.builtin.apt:
    name: vault
    state: latest

- name: Configure Vault
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: '0644'
  become: true

- name: Start and enable vault
  become: true
  ansible.builtin.service:
    name: vault
    state: started
    enabled: true

- name: Initialize Vault
  ansible.builtin.command: vault operator init -address=http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8200
  register: vault_tokens

- debug:
    var: vault_tokens.stdout_lines

- name: Pause until you can verify recording of vault tokens
  ansible.builtin.pause:
    prompt: "Verify that the vault tokens have been saved."