---
# tasks file for sft.docker

- name: Install Docker dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: latest

- name: Add Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /usr/share/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/debian bullseye stable
    filename: docker
    state: present
    update_cache: true

- name: Install Docker
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: Start and enable the docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
    