---
# tasks file for sft.python3

- name: Install python3
  become: true
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-full
      - python3-apt
      - python3-pip
      - python3-psycopg2
      - pipx
      - virtualenv
    state: latest
  tags:
    - python3
    - software