---
# tasks file for nmd.mariadb
- name: Check what volumes exist
  become: true
  ansible.builtin.command:
    argv:
      - /usr/bin/nomad
      - volume
      - status
  run_once: true
  register: volume_status

- name: Ensure remote volumes directory exists
  become: true
  ansible.builtin.file:
    path: /opt/nfs-volumes
    state: directory
  when: nomad_leader == true and not 'mariadb' in volume_status.stdout
  tags: nomad-mariadb

- name: Copy the mariadb volume file to the remote machine
  become: true
  ansible.builtin.copy:
    src: 'mariadb.volume'
    dest: /opt/nfs-volumes/
    owner: root
    group: root
  run_once: true
  when: nomad_leader == true and not 'mariadb' in volume_status.stdout
  tags: nomad-mariadb

- name: Deploy the mariadb volume
  become: true
  ansible.builtin.command:
    argv:
      - /usr/bin/nomad
      - volume
      - create
      - /opt/nfs-volumes/mariadb.volume
  run_once: true
  when: nomad_leader == true and not 'mariadb' in volume_status.stdout
  tags: nomad-mariadb

- name: Deploy the mariadb nomad job
  community.general.nomad_job:
    host: localhost
    state: present
    content: "{{ lookup('ansible.builtin.file', '../nomad/mariadb.nomad') }}"
    timeout: 120
    use_ssl: false
  run_once: true

- name: Wait for mariadb to come up
  ansible.builtin.wait_for:
    #port: 5432
    #delay: 10
    sleep: 10
    #state: present
    #timeout: 100